config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  resources :posts, only: %i(index new create show destroy)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :video,presence: true
  
  mount_uploader :video, VideoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post,only: %i(show destroy)
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path, notice: '投稿しました'
    else
      render :new
    end
  end 
    
  def index 
    @posts = Post.all.order('created_at DESC')
  end 
  
  def show
  end 
  
  def destroy
    redirect_to root_path, notice: '削除しました' if @post.destroy
  end 
    
    private
    def post_params
      params.require(:post).permit(:title, :body, :video)
    end
    
    def set_post
      @post = Post.find_by(id: params[:id])
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechpitMovie</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partial/navbar' %>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<P>このページは仮のトップページです。</P>
<%= link_to "仮のボタンです", "#", class: "btn btn-primary" %>

app/views/partial/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to "テクピト動画", root_path, class: "navbar-brand" %>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <%= link_to '新規投稿', new_post_path, class: "new-post btn btn-secondary" %>
        </form>
      </div>
    </nav>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<ul class="list-unstyled">
  <% @posts.each do |post| %>
  <li class="media">
    <%= link_to post_path(post) do %>
    <%= video_tag post.video.to_s, :size => "360x200" %>
    <% end %>
    
    <div class="media-body">
     <%= link_to post_path(post) do %>
      <h5 class="mt-0 mb-1"><%= post.title %></h5>
     <% end %>
      <%= post.body %>
    </div>
  </li>
  <% end %>
</ul>

app/views/posts/new.html.erb
<%= form_with(model: @post, local: true) do |form| %>
  <div class="form-group">
    <%= form.text_field :title, placeholder: "タイトル" %>
  </div>
  <div class="form-group">
    <%= form.text_area :body, placeholder: "動画の説明" %>
  </div>
  <div class="form-group">
    <%= form.file_field :video %>

  </div>
  <%= form.submit class: "btn btn-primary"%>
<% end %>

app/views/posts/show.html.erb
<div>
  <h1><%= @post.title %></h1>
</div>

<div>
  <p><%= @post.body %></p>
</div>
<div id="nicoscreen">
  <iframe width="1024" height="576" src="<%= @post.video.to_s %>"frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

<input type="text" id="comment_text">
<button id="comment_button" class="btn btn-secondary">コメント</button>

<div>
  <%= link_to '削除', @post, method: :delete, data: { confilm: '削除しますか?' } %>
</div>
    
<div id="comment_list">
  <ul id="list" class="list-group">
  </ul>
</div>